server:
  port: 80
# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.205.136:3306/firstDB
    username: ldh
    password: ldh
    # sql-script-encoding: sql-script-encoding=utf-8
  #jpa 打印sql
  jpa:
    show-sql: true
  #redis集群配置
  redis:
    cluster:
      nodes:
      - 192.168.205.178:7001
      - 192.168.205.178:7002
      - 192.168.205.178:7003
      - 192.168.205.178:7004
      - 192.168.205.178:7005
      - 192.168.205.178:7006
      max-redirects: 3  #获取失败 最大重定向次数
    # jedis:
    #   pool:
    #     max-active: 1000  # 连接池最大连接数（使用负值表示没有限制)
    #     max-idle: 10    # 连接池中的最大空闲连接
    #     max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    #     min-idle: 5     # 连接池中的最小空闲连接
    timeout: 6000  # 连接超时时长（毫秒）


hello:
    mesg: ldh
    mesg1: bhq