server:
  port: 8761
eureka:
  # server:
  #   enable-self-preservation: false  自我保护机制配置，默认为true开启
  client:
    register-with-eureka: false    #注册中心服务不显示在列表中
    service-url:
      defaultZone: http://localhost:8761/eureka/
      #      defaultZone: http://localhost:8762/eureka/ 集群
#设置服务名称
spring:
  application:
    name: eureka-server1